In [1]:
import pandas as pd

def load_and_display_data(data_filename, predictions_filename):
  data_df = pd.read_csv(data_filename)
  predictions_df = pd.read_csv(predictions_filename)
  display(data_df)
  display(predictions_df)

In [2]:
base = "results/"
data_filename = base + "scores.csv"
predictions_filename = base + "predictions.csv"
load_and_display_data(data_filename, predictions_filename)

       q      p1      p2      p3  market
0   0.00 -0.0000 -0.0000 -0.0000 -0.0000
1   0.05 -0.0475 -0.0475 -0.0475 -0.0475
2   0.10 -0.0819 -0.0835 -0.0900 -0.0838
3   0.15 -0.1204 -0.1229 -0.1268 -0.1223
4   0.20 -0.1539 -0.1575 -0.1588 -0.1558
5   0.25 -0.1824 -0.1849 -0.1873 -0.1840
6   0.30 -0.2060 -0.2095 -0.2095 -0.2078
7   0.35 -0.2248 -0.2269 -0.2269 -0.2260
8   0.40 -0.2400 -0.2400 -0.2400 -0.2400
9   0.45 -0.2475 -0.2475 -0.2475 -0.2475
10  0.50 -0.2500 -0.2500 -0.2500 -0.2500
11  0.55 -0.2475 -0.2475 -0.2475 -0.2475
12  0.60 -0.2400 -0.2400 -0.2400 -0.2400
13  0.65 -0.2248 -0.2269 -0.2269 -0.2260
14  0.70 -0.2059 -0.2095 -0.2095 -0.2075
15  0.75 -0.1824 -0.1849 -0.1873 -0.1840
16  0.80 -0.1539 -0.1564 -0.1588 -0.1555
17  0.85 -0.1204 -0.1229 -0.1268 -0.1223
18  0.90 -0.0819 -0.0828 -0.0900 -0.0835
19  0.95 -0.0475 -0.0475 -0.0475 -0.0475
20  1.00 -0.0000 -0.0000 -0.0000 -0.0000

       q    p1    p2    p3  market  final
0   0.00  0.00  0.00  0.00    0.00   0.00
1   0.05  0.05  0.05  0.05    0.05   0.05
2   0.10  0.09  0.05  0.00    0.05   0.09
3   0.15  0.14  0.09  0.06    0.10   0.14
4   0.20  0.19  0.13  0.12    0.15   0.19
5   0.25  0.24  0.19  0.17    0.20   0.24
6   0.30  0.28  0.23  0.23    0.25   0.29
7   0.35  0.32  0.29  0.29    0.30   0.34
8   0.40  0.40  0.40  0.40    0.40   0.40
9   0.45  0.45  0.45  0.45    0.45   0.45
10  0.50  0.50  0.50  0.50    0.50   0.50
11  0.55  0.55  0.55  0.55    0.55   0.55
12  0.60  0.60  0.60  0.60    0.60   0.60
13  0.65  0.68  0.71  0.71    0.70   0.66
14  0.70  0.71  0.77  0.77    0.75   0.71
15  0.75  0.76  0.81  0.83    0.80   0.76
16  0.80  0.81  0.86  0.88    0.85   0.81
17  0.85  0.86  0.91  0.94    0.90   0.86
18  0.90  0.91  0.94  1.00    0.95   0.91
19  0.95  0.95  0.95  0.95    0.95   0.95
20  1.00  1.00  1.00  1.00    1.00   1.00